name: GitHub Actions Build Docker run Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t news-api:latest .

      - name: Save Docker Image as Tar
        run: docker save news-api:latest -o news-api.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-api-image
          path: news-api.tar


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: news-api-image

      - name: Load Docker Image
        run: docker load -i news-api.tar

      - name: Run Tests in Container
        run: |
          docker run --rm \
          -e DATABASE_HOST=postgres \
          -e DATABASE_PORT=5432 \
          -e DATABASE_USER=postgres \
          -e DATABASE_PASSWORD=password \
          news-api:latest \
          sh -c "npm install --only=dev && npm test"
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: password
